name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #주석
    - uses: actions/checkout@v2 
      with: #개인토큰사용여부
        persist-credentials: false
    - name: 1. pip upgrade 
      run: python -m pip install --upgrade pip
    - name: 2. python pakage install
      run: pip install -r requirements.txt
    - name: 3. python execute
      run: python crawing_basic.py
    - name: Commit files
      run: |
        git config --local user.email "howerll12@gmail.com"
        git config --local user.name "howerll12[bot]"
        git add .
        git commit -m "Run crawler and update current data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
