name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #주석
    - uses: actions/checkout@v2
    - name: file print
      run: ls
    - name: python pakage check
      run: pip list 
    - name: python execute
      run: python test.py
