name: sub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 변수출력 
      env:
        NAME: "alum.lee"
      run: echo "내 이름은 $NAME 입니다."
    - name: 2. 변수출력 
      env:
        ID: ${{ github.actor }}
      run: echo "내 이름은 $NAME이고 ID는 $ID 입니다."
